server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS dbep001;"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    validation-query: 'SELECT 1'
    validation-interval: 30000
    time-between-eviction-runs-millis: 30000
    max-active: 200
    min-idle: 8
    max-idle: 10
    max-wait: 10000
    initial-size: 10
    remove-abandoned-timeout: 7200
    min-evictable-idle-time-millis: 30000
    suspect-timeout: 7200
    remove-abandoned: true
    test-on-borrow: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  autoconfigure:
    exclude: 'none'
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    check-location: false
    enabled: true
  application:
    name: "blood-donation"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

context:
  holder:

application:
  name: "blood-donation"

build:
  version: "1.0"